# 使用官方的 Nginx 镜像作为基础镜像
FROM nginx:alpine

# 删除默认的 Nginx 配置文件
RUN rm /etc/nginx/conf.d/default.conf

# 复制自定义的 Nginx 配置文件到容器中
COPY nginx/nginx.conf /etc/nginx/conf.d/

# 复制 SSL 证书到容器中
COPY nginx/certs /etc/nginx/ssl

# 暴露端口 8443
EXPOSE 8443

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
