services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8000:8000"
    environment:
      LISTEN_PORT: 8000
    env_file:
      - ./backend/py/.env
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "8443:8443"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
